#cloud-config
runcmd:
- PLACEMENT=`curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone | awk '{ print substr($1, 1, length($1)-1) }'`
- aws configure set default.region $PLACEMENT
- aws configure set default.output text
- INSTANCE_ID=`/opt/aws/bin/ec2-metadata -i | awk '{ print $2 }'`
- IP_ADDRESS=`/opt/aws/bin/ec2-metadata -o | awk '{ print $2 }'`
- DOMAIN=`grep search /etc/resolv.conf | awk '{ print $2 }'`
- ENV=`aws ec2 describe-tags --filters "Name=resource-id,Values=$INSTANCE_ID" | awk '$2 ~ /^environment$/' | sed 's/.*\t//g'`
- ROLE=`aws ec2 describe-tags --filters "Name=resource-id,Values=$INSTANCE_ID" | awk '$2 ~ /^role$/' | sed 's/.*\t//g'`
- HOSTNAME=$ENV-$ROLE-i-packer
- FQDN=$HOSTNAME.$DOMAIN
- hostname $FQDN
- sed -i "s/HOSTNAME=localhost.localdomain/HOSTNAME=$FQDN/g" /etc/sysconfig/network
- echo "$IP_ADDRESS $FQDN" >> /etc/hosts
